
create table user_entity (
    user_id bigint generated by default as identity,
    user_active_status boolean not null,
    user_birth_date date not null,
    user_email varchar(255) not null,
    user_first_name varchar(255) not null,
    user_last_name varchar(255) not null,
    primary key (user_id));