
create table card_entity(
 card_id bigint generated by default as identity,
 card_active_status boolean not null,
 card_number varchar(255) not null,
 card_expiry_date date not null,
 card_holder_name varchar(255) not null,
 user_id bigint, primary key (card_id));
