CREATE TYPE order_status AS ENUM
(
    'APPROVED',
    'CREATED',
    'DELIVERED',
    'REJECTED'
);
CREATE CAST (VARCHAR AS order_status) WITH INOUT AS IMPLICIT;
CREATE CAST (order_status AS VARCHAR) WITH INOUT AS IMPLICIT;

CREATE TABLE order_entity (
                              order_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                              order_deleted BOOLEAN DEFAULT false,
                              status order_status NOT NULL,
                              order_price NUMERIC(38,2), user_id BIGINT,
                              PRIMARY KEY (order_id),
                              created_by               VARCHAR(100)               NOT NULL,
                              created_at               TIMESTAMP                  NOT NULL DEFAULT CURRENT_TIMESTAMP,
                              updated_by               VARCHAR(100),
                              updated_at               TIMESTAMP);