CREATE TABLE item_entity (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    item_name VARCHAR(255),
    item_price NUMERIC(38,2),
    PRIMARY KEY (item_id),
    created_by               VARCHAR(100)               NOT NULL,
    created_at               TIMESTAMP                  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR(100),
    updated_at               TIMESTAMP)