CREATE TABLE order_item_entity (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    item_id BIGINT,
    order_id BIGINT,
    order_item_quantity INTEGER,
    PRIMARY KEY (order_item_id),
    created_by               VARCHAR(100)               NOT NULL,
    created_at               TIMESTAMP                  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR(100),
    updated_at               TIMESTAMP);