apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dytni-ingress
  namespace: dytni

spec:
  ingressClassName: nginx

  rules:
    - host: api.dytni.local

      http:
        paths:
          - path: /
            pathType: Prefix

            backend:
              service:
                name: api-gateway
                port:
                  number: 8085