CREATE TYPE user_role AS ENUM ('ADMIN', 'USER');

CREATE TABLE user_entity (
                             user_id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
                             user_login           VARCHAR(255)   NOT NULL,
                             user_password        VARCHAR(255)   NOT NULL,
                             role                 user_role      NOT NULL,
                             user_active_status   BOOLEAN        NOT NULL DEFAULT TRUE,
                             created_by               VARCHAR(100)               NOT NULL,
                             created_at               TIMESTAMP                  NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             updated_by               VARCHAR(100),
                             updated_at               TIMESTAMP,
                             CONSTRAINT pk_user_entity PRIMARY KEY (user_id),
                             CONSTRAINT uk_user_entity_login UNIQUE (user_login)
);