apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db
  namespace: dytni
spec:
  replicas: 1

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: mongo-db

  template:
    metadata:
      labels:
        app: mongo-db

    spec:
      containers:
        - name: mongo
          image: mongo:7.0

          ports:
            - containerPort: 27017

          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db

          startupProbe:
            exec:
              command:
                - mongosh
                - --quiet
                - --eval
                - "db.adminCommand('ping').ok"
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 30

          livenessProbe:
            exec:
              command:
                - mongosh
                - --quiet
                - --eval
                - "db.adminCommand('ping').ok"
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            exec:
              command:
                - mongosh
                - --quiet
                - --eval
                - "db.adminCommand('ping').ok"
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3

      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc