spring.application.name=auth

spring.datasource.url=${POSTGRES_AUTH_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/auth
spring.flyway.validate-on-migrate=true
spring.flyway.table=flyway_schema_history
spring.flyway.create-schemas=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
server.port=${AUTH_SERVICE_PORT}

jwt.secret=${JWT_SECRET}
jwt.access.expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION}