apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: dytni
spec:
  replicas: 1

  selector:
    matchLabels:
      app: api-gateway

  template:
    metadata:
      labels:
        app: api-gateway

    spec:
      containers:
        - name: api-gateway
          image: api-gateway:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 8085

          envFrom:
            - configMapRef:
                name: app-config

            - secretRef:
                name: app-secrets

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8085

            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8085

            initialDelaySeconds: 45
            periodSeconds: 10