
CREATE TABLE user_entity (
    user_id                  BIGINT             GENERATED BY DEFAULT AS IDENTITY,
    user_active_status       BOOLEAN NOT NULL,
    user_birth_date          DATE NOT NULL,
    user_email               VARCHAR(255) NOT NULL UNIQUE ,
    user_first_name          VARCHAR(255) NOT NULL,
    user_last_name           VARCHAR(255) NOT NULL,
    PRIMARY KEY (user_id),
    created_by               VARCHAR(100)               NOT NULL,
    created_at               TIMESTAMP                  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR(100),
    updated_at               TIMESTAMP);