
CREATE TABLE card_entity(
 card_id                  BIGINT         GENERATED BY DEFAULT AS IDENTITY,
 card_active_status       BOOLEAN                    NOT NULL DEFAULT TRUE,
 card_number              VARCHAR(255)               NOT NULL UNIQUE,
 card_expiry_date         DATE                       NOT NULL,
 card_holder_name         VARCHAR(255)               NOT NULL,
 user_id                  BIGINT,
 PRIMARY KEY (card_id),
 created_by               VARCHAR(100)               NOT NULL,
 created_at               TIMESTAMP                  NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_by               VARCHAR(100),
 updated_at               TIMESTAMP);
