name: CI Pipeline

on:
  push:
    branches:
      - "**"

jobs:

  build:
    name: Build application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven


      - name: Build with Maven
        run: mvn clean package -DskipTests


  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: build

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven


      - name: Run tests
        run: mvn test


  sonar:
    name: Sonar analysis
    runs-on: ubuntu-latest
    needs: test

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven


      - name: Sonar Scan
        run: |
          mvn clean verify sonar:sonar \
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}


  docker:
    name: Build Docker images
    runs-on: ubuntu-latest
    needs: sonar

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven


      - name: Build jar files
        run: mvn clean package -DskipTests

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build auth image
        run: |
          docker build \
          -f auth/Dockerfile \
          -t ${{ secrets.DOCKER_USERNAME }}/innovise-project-auth-service:latest .

      - name: Build user-service image
        run: |
          docker build \
          -f user-service/Dockerfile \
          -t ${{ secrets.DOCKER_USERNAME }}/innovise-project-user-service:latest .


      - name: Push auth image
        run: |
          docker push \
          ${{ secrets.DOCKER_USERNAME }}/innovise-project-auth-service:latest


      - name: Push user-service image
        run: |
          docker push \
          ${{ secrets.DOCKER_USERNAME }}/innovise-project-user-service:latest